// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbdn3Z-38IeVflxg5z70AT6Uerwbp7QeI',
    appId: '1:20568286643:web:29a9f2b7619cb4452017c6',
    messagingSenderId: '20568286643',
    projectId: 'flutterclone-58f5a',
    authDomain: 'flutterclone-58f5a.firebaseapp.com',
    storageBucket: 'flutterclone-58f5a.appspot.com',
    measurementId: 'G-FRQM6WZ62Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4uKtVhNRPNnmXy1Z2OUQKexmAR5P_KQ',
    appId: '1:20568286643:android:189570fd92451b1a2017c6',
    messagingSenderId: '20568286643',
    projectId: 'flutterclone-58f5a',
    storageBucket: 'flutterclone-58f5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrha5kstNdxuJ94kuyHFB_4qJ7YQZV4GU',
    appId: '1:20568286643:ios:548b9dc8aa45771a2017c6',
    messagingSenderId: '20568286643',
    projectId: 'flutterclone-58f5a',
    storageBucket: 'flutterclone-58f5a.appspot.com',
    iosClientId: '20568286643-fc1jjguihrb1lefekime2bslbt0bhjml.apps.googleusercontent.com',
    iosBundleId: 'com.example.finals1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrha5kstNdxuJ94kuyHFB_4qJ7YQZV4GU',
    appId: '1:20568286643:ios:548b9dc8aa45771a2017c6',
    messagingSenderId: '20568286643',
    projectId: 'flutterclone-58f5a',
    storageBucket: 'flutterclone-58f5a.appspot.com',
    iosClientId: '20568286643-fc1jjguihrb1lefekime2bslbt0bhjml.apps.googleusercontent.com',
    iosBundleId: 'com.example.finals1',
  );
}
